default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: thinkific_development

test:
  <<: *default
  database: thinkific_test

production:
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
